#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-http-builder
Version  : 0.7.2
Release  : 2
URL      : https://github.com/jgritman/httpbuilder/archive/http-builder-0.7.2.tar.gz
Source0  : https://github.com/jgritman/httpbuilder/archive/http-builder-0.7.2.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-http-builder-data = %{version}-%{release}

%description
HTTPBuilder = Easy HTTP client for Groovy.
http://groovy.codehaus.org/modules/http-builder

%package data
Summary: data components for the mvn-http-builder package.
Group: Data

%description data
data components for the mvn-http-builder package.


%prep
%setup -q -n httpbuilder-http-builder-0.7.2

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.jar
/usr/share/java/.m2/repository/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom
